export const experiences = [
  {
    position: 'Développeuse FullStack JS',
    date: 'Avr 2024 - Présent',
    company: 'AZ+',
    responsibilities: [
      'Développement backend d’une plateforme e-commerce',
      'Intégration et développement (back-end et front-end) du back-office',
      'Documentation technique et mise en place des tests unitaires avec Jest',
      'Adoption de méthode Agile',
      'Participation au daily meeting, review et rétro de chaque sprint',
      'Utilisation de l’architecture microservices et des concepts BFF',
    ],
    skills: [
      'Nest.js',
      'Next.js',
      'PostgreSQL',
      'Prisma ORM',
      'API RESTful',
      'Microservices',
      'BFF',
      'Swagger',
      'Agile',
    ],
  },
  {
    position: 'Développeuse FullStack JS',
    date: 'Déc 2023 - Avr 2024',
    company: 'RELIA Consulting',
    responsibilities: [
      'Conception et développement d’une plateforme de mentoring (NestJS, Next.js, MongoDB)',
      'Rédaction de la documentation technique et des API backend (Swagger)',
      'Mise en oeuvre des API RESTful',
      'Gestion des bases de données avec MongoDB et Mongoose',
    ],
    skills: [
      'Nest.js',
      'Next.js',
      'MongoDB',
      'Mongoose',
      'API RESTful',
      'Swagger',
    ],
  },
  {
    position: 'Stagiaire développeur',
    date: 'Août 2023 - Nov 2023',
    company: 'RELIA Consulting',
    responsibilities: [
      'Conception et développement d’une plateforme de mentoring (NestJS, Next.js, MongoDB)',
      'Rédaction de la documentation technique et des API backend (Swagger)',
      'Mise en oeuvre des API RESTful',
      'Gestion des bases de données avec MongoDB et Mongoose',
    ],
    skills: [
      'Nest.js',
      'Next.js',
      'MongoDB',
      'Mongoose',
      'API RESTful',
      'Swagger',
    ],
  },
  {
    position: 'Développeuse PHP',
    date: 'Juin 2022 - Mars 2023',
    company: 'ALEA',
    responsibilities: [
      "Participation au développement de l'application de gestion de l'établissement AST Androhibe",
      'Mise en oeuvre de la gestion des professeurs et étudiants',
      'Gestion des cours, des présences et des frais de scolarité des étudiants',
      "Mise en place d'un système de parrainage des étudiants",
    ],
    skills: ['PHP', 'CodeIgniter', 'PostgreSQL', 'Bootstrap', 'HTML', 'CSS'],
  },
]
